[package]
name = "wallet-cell-type-generator"
version = "0.1.0"
authors = ["Link <xieaolin@gmail.com>"]
edition = "2018"

[dependencies]
das-types = { path = "../../das-types/rust", features = ["std"] }
faster-hex = "0.5.0"
